### ISSUE TITLE
Using ss_oled at i2c1

### ISSUE THREAD

**Issue by kaefe64** [bitbank2/Pi_Pico_C_Projects#1]
Hi, great lib, thanks.
I am using the I2C1 GP19 SCL and GP18 SDA in my hardware.
It is possible to change the I2C pins in the code, but not the I2C port.
As a suggestion, include a iOLED_I2C_PORT in BBI2C, and change all i2c0 references to pI2C->iOLED_I2C_PORT.

typedef struct mybbi2c
{
uint8_t iSDA, iSCL; // pin numbers (0xff = disabled)
uint8_t bWire; // use the Wire library
i2c_inst_t *iOLED_I2C_PORT;   // <------  to choose i2c0 or i2c1
uint8_t iSDABit, iSCLBit; // bit numbers of the ports
uint32_t iDelay;
} BBI2C;

**Comment by bitbank2** [comment]
Thanks for the suggestion. I think it would be best to keep a fork of this repo and do the changes you want for your projects. I have been mostly focused on Arduino code and not the Pico SDK.
